### ISSUE TITLE
Can you please add REV file not only RIV in example

### ISSUE THREAD

**Issue by danilof** [FilledStacks/expression-ui#14]
Hi @FilledStacks,

this looks really good and promising :)
Can you also add rev file to flutter example folder that we can play with it a little bit? This would be amazing.
I can hardly wait to get newsletter regarding expressionui.

Best Regards,
Danilo

**Comment by FilledStacks** [comment]
Hey,

I don't quite know what you're asking for here. 

We only using the .riv file for the UI in the example app, which you can run and now for Flutter to see the working example onboarding flow built with ExpressionUI.

**Comment by pjarnfelt** [comment]
It's about the working Rive editor file to see the setup of e.g. layout constraints. 
The .riv file cannot be opened in the Rive editor

**Comment by FilledStacks** [comment]
I didn't even know there's 2 different files 😅

The desktop app isn't allowing me to export a `.rev` file. 

I'll try the web app.

**Comment by FilledStacks** [comment]
Exported below is the expression-ui file. 

The responsive-template artboard is on the far right. You can copy that and paste it in the rive file that you want to build responsive UI's in. 

There's currently a bug in ExpressionUI with responsive UI's where events don't fire, I've opened a [issue on the rive repo](https://github.com/rive-app/rive-flutter/issues/402)

[expression-ui.zip](https://github.com/user-attachments/files/15914993/expression-ui.zip)
